# JwtException 응답 처리
Jwt를 검증하는 과정에서 에러가 발생할 시 JwtException이 발생
+ 시큐리티 필터 내에서 발생한 에러기 때문에 GlobalExceptionHandler도 못잡는 상황이 발생하기 때문에 Exception이 터짐

## 1
JwtAuthenticationFilter 바로 뒤에 커스텀한 JwtExceptionFilter을 하나 더 만들어
JwtException이 터질 시 JwtExceptionFilter에서 예외를 정해진 응답에 맞게 처리
### 응답이 나가긴 나가나 두번이 나가는 사태

## 2
Jwt 예외가 발생함과 동시에 authenticationEntryPoint에서 잡고 UnAuthorizeException(커스텀처리한 401에러)가 터지고 필터까지 실행되기 때문에 응답 2번
+ authenticationEntryPoint 부분을 시큐리티에서 제거

### Body는 내 생각대로 찍히나 status가 문제였다.
-> 이제는 403이 찍히는 문제...에러 메시지로는 Access Denied이 뜨는 문제를 해결해야 함

## 다시 돌아와서 지금 문제는 뭘까?

1. authenticationEntryPoint에서는 JwtException를 처리를 못한다.
2. JwtException이 터지면 HandlerExceptionResolver가 잡아서 처리한다.(Jwt에 문제가 있다 -> 인증이 안된 것이기 때문에 인증예외도 터짐 -> 이 AuthenticationEntryPoint에게 잡힘)
3. 이때 JwtException로 HandlerExceptionResolver에게 전달되는 것이 아닌 InsufficientAuthenticationException로 잡힌다.
 
## 헷갈렸던 부분

+ JwtException은 AuthenticationException이 아니다.
+ 따라서 AuthenticationEntryPoint에서 잡히는 건 JwtException이 아닌 JwtException 때문에 발생된 InsufficientAuthenticationException이다.
그렇다면 어떻게 해야할까?

## 3

최고의 선택인지는 모르겠지만 나는 다음의 방법을 선택했다. (최선이라고 생각...)

1. AuthenticationEntryPoint에서 잡힐 만한 부분을 최대한 예외처리
2. JwtException 등 AuthenticationFilter에서 예외 발생
3. sendError 실행
 + sendError는 서블릿 컨테이너에 실제 오류가 발생했다고 알려주는 역할
4. JwtExceptionFilter가 앞서 발생한 예외에 대해 응답을 처리

## 로그를 보면 실행 순서는 이전과 동일하다.

+ JwtAuthenticationFilter에서 JwtException 발생 -> authenticationEntryPoint -> JwtExceptionFilter

authenticationEntryPoint는 오류가 발생했다만 처리하고 응답에 대한 처리는 하지 않기 때문에 두번 Body가 적혀지는 현상은 해결했다.